A/A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/',include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

A/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name='user_register'),
    path('logout/', views.user_logout, name='user_logout'),
]

A/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.all_articles, name='all_articles' ),
    path('<int:id>/<slug:slug>', views.article_detail, name='article_detail' )
]

A/accounts/models.py
from django.db import models

# Create your models here.

A/blog/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User 
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class Articles(models.Model):
    STATUS = (
        ('draft','Draft'),
        ('publish','Publish')
    )
    title = models.CharField(max_length = 120) 
    slug = models.SlugField(max_length = 120, unique = True)
    writer = models.ForeignKey(User, on_delete = models.CASCADE)
    body = RichTextUploadingField()
    #body = models.TextField()
    publish = models.DateTimeField(default = datetime.now)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length= 20, choices = STATUS, default = 'draft')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[self.id , self.slug])

A/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserLoginForm(forms.Form):
    username = forms.CharField(label='username or email',max_length=30, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'your username'}))
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'your password'}))


class UserRegistrationForm(forms.Form):
    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'your username'}))
    email = forms.EmailField(max_length=50, widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'your email'}))
    password = forms.CharField(label='password', max_length=30, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'your password'}))
    password2 = forms.CharField(label='confirm password', max_length=30, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'your password'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email)
        if user.exists():
            raise forms.ValidationError('this email already exists')
        return email
    
    # Way 1 : password
    """
    def clean_password2(self):
        p = self.cleaned_data['password']
        p2 = self.cleaned_data['password2']
        if p != p2 :
            raise forms.ValidationError('passwords must match')
        return p
    """

    # Way 2 : password
    def clean(self):
        cleaned_data = super().clean()
        p = cleaned_data.get('password')
        p2 = cleaned_data.get('password2')
        if p and p2 :
            if p != p2 :
                raise forms.ValidationError('passwords must match')

        

A/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserLoginForm, UserRegistrationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username= form.cleaned_data['username']
            password= form.cleaned_data['password']
            user = authenticate(request, username= username, password= password)
            if user is not None:
                login(request, user)
                messages.success(request, 'you logged in successfully !','success')
                return redirect('blog:all_articles') 
            else :
                messages.error(request, 'wrong yousername or password !','warning')          
    else:
        form = UserLoginForm()
    
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data  #copy all cleaned data
            User.objects.create_user(cd['username'],cd['email'],cd['password'])
            messages.success(request,'you registered successfuly, now log in', 'success')
            return redirect('accounts:user_login')
    else:
        form = UserRegistrationForm()
    context = {'form':form}
    return render(request, 'accounts/register.html', context)



def user_logout(request):
    logout(request)
    messages.success(request,'you logout successfuly', 'success')
    return redirect('blog:all_articles')

A/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Articles

def all_articles(request):
    all_articles = Articles.objects.filter(status='publish')
    context = {'all_articles' : all_articles}
    return render (request, 'blog/all_articles.html', context)


def article_detail(request, id, slug):
    #article = Articles.objects.get(id = id , slug = slug)
    article = get_object_or_404(Articles,id = id , slug = slug )
    context = {'article': article}
    return render (request, 'blog/article.html', context)

A/accounts/templates/accounts/login.html
{% extends 'base.html' %}



{% block content %}
    <div class="card">
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
            </form>

        
    </div>
{% endblock %}

A/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="card">
        <form action="" method="POST" >
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="register" class="btn btn-primary">
            </form>      
    </div>
{% endblock %}

A/blog/templates/blog/all_articles.html
{% extends 'base.html' %}



{% block content %}

    <div class="card">
    {% for article in all_articles %}
        <a href="{{ article.get_absolute_url }}" class="card-body">{{ article.title }}</a>
    {% endfor %}
    </div>

{% endblock %}

A/blog/templates/blog/article.html
{% extends 'base.html' %}



{% block content %}
    <div class="card">
        <h3>{{ article.title }}</h3>
        <small>{{ article.publish|timesince }}</small>
        <p>{{ article.body|safe }}</p>
        
    </div>
{% endblock %}

A/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %} " />  
<meta charset='UTF-8'>
    <title> Blog</title>
</head>
<body>
    {% include 'inc/navbar.html' %}
    
    <div class="jumbotron">
    {% include 'inc/messages.html' %}
    {% block content %}{% endblock %}
    </div>
</body>
</html>

A/templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
	    <p class='alert alert-{{message.tags}}' > {{ message }} </p>
    {% endfor %}
{% endif %}

A/templates/inc/navbar.html
<nav class="navbar navbar-expend-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'blog:all_articles' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'accounts:user_logout' %}">logout</a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'accounts:user_login' %}">Login</a>
        <a class="nav-item nav-link" href="{% url 'accounts:user_register' %}">Register</a>
        {% endif %}
    </div>
</nav>